require:
  - rubocop-rails
  - rubocop-performance

Style/Documentation:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'test/application_system_test_case.rb'
    - 'test/test_helper.rb'
    
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
