require:
  - rubocop-rails
  - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
    
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
